const BLOCK_PLAY = "BLOCK_PLAY"
const ADD_BALL = "ADD_BALL"
const ADD_NEXT_BALLS = "ADD_NEXT_BALLS"
const UNLOCK_PLAY = "UNLOCK_PLAY"
const SET_SELECTED_BALL = "SET_SELECTED_BALL"
const MOVE_BALL = "MOVE_BALL"
const PREPARE_REMOVED_BALLS = "PREPARE_REMOVED_BALLS"
const REMOVE_BALLS = "REMOVE_BALLS"

export { BLOCK_PLAY, ADD_BALL, ADD_NEXT_BALLS, UNLOCK_PLAY, SET_SELECTED_BALL, MOVE_BALL, PREPARE_REMOVED_BALLS, REMOVE_BALLS }