const BLOCK_PLAY = "BLOCK_PLAY"
const ADD_BALL = "ADD_BALL"
const ADD_NEXT_BALLS = "ADD_NEXT_BALLS"
const UNLOCK_PLAY = "UNLOCK_PLAY"
const SET_SELECTED_BALL = "SET_SELECTED_BALL"

export { BLOCK_PLAY, ADD_BALL, ADD_NEXT_BALLS, UNLOCK_PLAY, SET_SELECTED_BALL }